spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.201.103.135:3306/yuaga
    username: root
    password: 12345678

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  redis:
    port: 6379
    host: 43.201.103.135

jwt:
  secret_key: djikakdfjasilohgisaughfiojznbhrhiudawjhgbvfbreuadijs
  access_exp: 3600
  refresh_exp: 86400
  header: Authorization
  prefix: Bearer